### ISSUE TITLE
Language selection + resource for easy translation

### ISSUE THREAD

**Issue by wolfie24** [scelts/msfslandingrate#10] opened 2020-10-28 13:56 UTC
Hi, my name is Daniel ("Wolf " for the fellows) and I an enthusiast of flight simulators. 
I have contributed on several occasions to translate programs or articles into Spanish that I found interesting.
Thanks to a YouTube channel on MSFS2020 in Spanish (https://www.youtube.com/results?search_query=%23MSFS2020) I have found out about your program, and of the two shown on that site, yours seemed the most practical and easy to use.
I would be interested in having the possibility of having it in my native language, Spanish (Spanish from Argentina, which also works for any other country that speaks my language).
If you are interested, you only need to send me the sentences to translate and I will gladly do so. This will not only benefit the community I am in but it will broaden the horizon of dysfusion of your program.
I have not seen a separate file with text strings, maybe this would allow you to add many other languages ​​as the flight simulation community grows day by day.
Among the programs that I translated into Spanish (at that time only usable by X-Plane) are LittleNavMap, Landing Rate, some Ortho4XP manuals, AlpilotX meshes, etc.
I remain at your disposal if you are interested, cordial greetings from the South of Argentina!

**Comment by scelts** [comment] 2020-10-28 14:41
Hi Wolf,
Gladly, thanks! I'll keep this open since I would need to create some kind of resource where one can change the language so that you can easily update it for Spanish.
Will ping you once it's done, I didn't have much time to work on this the last days.

**Comment by wolfie24** [comment] 2020-10-28 15:39
Thank you !. I look forward to when you can if you are still interested. In
the meantime I will enjoy your program! Today I have a great challenge,
landing right now in the city of Rio Gallegos (250Km from where I live)
with winds of 50KM / Hour and gusts of 80 (31 to 50 MPH!), your program
will come in handy to perfect my landing. Great job!

Daniel "Wolf"
________________________________________________________________________________
*Wolf Informática*
*Visítenos en los siguientes sitios:*

   - *Sitio Web  http://wolfinformatica.com <http://wolfinformatica.com/>*
   - *Facebook  www.facebook.com/servicewolf
   <http://www.facebook.com/servicewolf> *
   - *Twitter      @servicewolf <http://twitter.com/servicewolf>*
   - *e-Mail        info@wolfinformatica.com <info@wolfinformatica.com>*
   - *Skype       wolfinformatica*

**Comment by scelts** [comment] 2020-11-01 15:37
Hi again,

Today I was working on some bugs and features and was also thinking to implement the language change, but I came to a realisation: The interface will change, this is by no means a finished app or anything!

So, the problem with the translation will be - I change functionality, and this requires an interface change to reflect it (i.e. today I changed the string "Auto close after" to "Auto close - bounce timer". If I have one language I understand, I can change this easily. But, if I have 5, of which 4 I can't understand, this becomes a problem! I would need to ping all the translators before publishing anything, to translate all the changes to all the languages, and this will be an issue if it would even be possible. Especially with an app like this, where it's much more important to have a quick fix or functionality update, than a translated interface.

Hope you understand, but I'm closing this for now. Once (if ever) there is a fixed interface and a long-run plan, I will for sure implement multi-language support and notify everyone.

**Closed as completed by scelts** 2020-11-01 15:37 UTC
Labels: enhancement

**Comment by wolfie24** [comment] 2020-11-01 19:05
Hello friend, I continue using your program and it is very good to help
improve the track touches - something I am not good at! -

Regarding translations, I will tell you what I have seen with some with
whom I worked and it seems that it has given them results because they
interface with many languages.

They usually have a file with numbering in their rows (an example only) and
each number corresponds to a phrase. This is how you put a folder with the
name of the languages in text format, such as spanish.txt english.txt
brasilian.txt francais.txt deustch.txt etc ...

For example, in each text file, the string 0001 corresponds to the same
translation option, so each translator simply takes their text file
(usually the original in English) and only changes the words from English
to their language.

spanish.txt
0001 Options (for the Spanish language)

english.txt
0001 Options (for English language)

brasilian.txt
0001 opções (for the Portuguese or Brazilian language)

deustche.txt
0001 Optionen (for German language)

and so with the rest of those you want to put. Then simply either
automatically or manually overwriting where you have arranged it, lang.txt
is used for the chosen language (that is, in my case I would translate from
English to Spanish and then I would put my file where the texts go by
changing the name to lang.txt, I don't know if I can explain myself)

Thus, with the organized text strings, you can make both the menus and the
texts that are presented.

I'm not saying it's easy, I've programmed in the 80's and I know that each
implementation involves a lot of changes in the rest and if it is not
thought from the beginning then it becomes a headache for the creator of
the program and it is a real chaos.

I just leave the comment if it helps you, maybe not for this program, but
maybe for the next one you do. Nowadays, although almost all of us
understand English, having a program in our native language makes us more
inclined to remain faithful to it. I say this from experience.

Likewise, I used a GitHub translation program several times, I really don't
remember what it's called, I haven't used it again for a long time, but
it's not a plain text format, it shows you all the organized strings and
they can be seen perfectly how are they; maybe you can investigate about
that if it seems correct to you.
I send you a big greeting from the South of Argentina!

Daniel "Wolf"
________________________________________________________________________________
*Wolf Informática*
*Visítenos en los siguientes sitios:*

   - *Sitio Web  http://wolfinformatica.com <http://wolfinformatica.com/>*
   - *Facebook  www.facebook.com/servicewolf
   <http://www.facebook.com/servicewolf> *
   - *Twitter      @servicewolf <http://twitter.com/servicewolf>*
   - *e-Mail        info@wolfinformatica.com <info@wolfinformatica.com>*
   - *Skype       wolfinformatica*

**Comment by scelts** [comment] 2020-11-01 19:18
Hi,

No this is not a problem - I was thinking of doing it this way, or using some .net feature where this could be done automatically.

The problem is that I will be changing the strings themself often. So in your example, for example, I change the string 
001: Options 
to 
001: System Settings
And in translations, it stays 001: opções 

This will happen at this stage of the app. Especially for sentences. Just now with the latest update I have changed:

Auto close after (seconds):
to 
Auto close - Bounce timer (s):

And I cannot publish the update until people translate this string to each of the languages.

So for now, multi-language support is not really something I can handle. This can be done only when the interface is more less fixed, and there are no plans to do much, often.

**Comment by wolfie24** [comment] 2020-11-01 19:27
OK friend, in any case, I appreciate your work and dedication to the
project. For my part, I am spreading it in all possible forums and among my
simmer friends.
Greetings and good week!

Daniel "Wolf"
________________________________________________________________________________
*Wolf Informática*
*Visítenos en los siguientes sitios:*

   - *Sitio Web  http://wolfinformatica.com <http://wolfinformatica.com/>*
   - *Facebook  www.facebook.com/servicewolf
   <http://www.facebook.com/servicewolf> *
   - *Twitter      @servicewolf <http://twitter.com/servicewolf>*
   - *e-Mail        info@wolfinformatica.com <info@wolfinformatica.com>*
   - *Skype       wolfinformatica*

**Comment by scelts** [comment] 2020-11-01 19:59
Thanks Daniel!

I'll make sure to reopen this and ping you once the multi-language support is on the table.
